[package]
name = "day7"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1"
thiserror = "1.0"
typed-path = "0.9"
indextree = "4.6"